[[local|localrc]]

DATABASE_PASSWORD=stackdb
ADMIN_PASSWORD=nomoresecrete
SERVICE_PASSWORD=$ADMIN_PASSWORD
# openssl rand -hex 10
SERVICE_TOKEN=thequickbrownfox
RABBIT_PASSWORD=stackqueue

DEST=/home/passwordlessuserondebian

HOST_IP=10.1.195.119
SERVICE_HOST="localhost" #see comments below
FLAT_INTERFACE=eth0
FIXED_RANGE=10.0.1.0/24
NETWORK_GATEWAY=10.0.1.1
FIXED_NETWORK_SIZE=254
export no_proxy=10.1.195.119,localhost,127.0.0.1,::1,10.0.1.*

# Logging
LOGFILE=$DEST/logs/stack.sh.log
VERBOSE=True
LOGDAYS=1
LOG_COLOR=False
SCREEN_LOGDIR=/opt/stack/logs

# All the services to be disabled/enabled
disable_service n-net
enable_service q-svc
enable_service q-agt
enable_service q-dhcp
enable_service q-l3
enable_service q-meta
enable_service neutron
enable_service heat,h-api,h-api-cfn,h-api-cw,h-eng
enable_service tempest

USE_SLL=True
SSL_ENABLED_SERVICES="key,nova,glance,cinder,neutron,heat"

# Neutron fails because the neutron server gives certificate with
# 'ghostrider' as name which fails to map with localhost as name.
#
# If neutron fails, then fix the lib/neutron's method to have
# --no-check-certificate in the wget command. Same for service that fail
# while devstack is waiting for them to come-up.
#
# OR
#
# in localrc, give SERVICE_HOST=<hostname> and hostname to no_proxy in
# local.conf and ~/.zshrc
# This hostname should match the hostname in /etc/hosts. Usually it is
# localhost or sometimes hostname.
#
# SERVICE_HOST=localhost
# no_proxy='localhost,blah,blah>
